name: Java CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout código
      uses: actions/checkout@v3

    - name: Configurar Java
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Compilar projeto
      run: javac Main.java

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Deploy simulado
      run: echo "Deploy realizado com sucesso 🚀"
